name: Criar Release Automática

on:
  push:
    tags:
      - 'v0'  # Ex: v1.0.0, v2.3.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Compactar a pasta 'gallery'
        run: |
          zip -r pacote-gallery.zip gallery

      - name: Criar Release com o pacote
        uses: softprops/action-gh-release@v2
        with:
          name: Lançamento ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: pacote-gallery.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
